spring.application.name=Pont-Commercial

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.port=${SERVER_PORT:8080}

jwt.secret=${JWT_SECRET}
jwt.expiration=900000
jwt.refresh-expiration=604800000

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

file.upload-dir=uploads/documents

stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}

billing.message-price=1.5
billing.currency=MAD

currency.api.key=${CURRENCY_API_KEY}
currency.api.url=${CURRENCY_API_URL}

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2s
spring.data.redis.connect-timeout=2s

logistics.api-key=${LOGISTICS_API_KEY}
logistics.api-url=${LOGISTICS_API_URL}
logistics.cost-per-km-usd=${LOGISTICS_COST_PER_KM_USD:2}
logistics.estimated-km-per-day=${LOGISTICS_ESTIMATED_KM_PER_DAY:700}

brevo.api-key=${BREVO_API_KEY}
brevo.from-email=${BREVO_FROM_EMAIL}
brevo.from-name=${BREVO_FROM_NAME}

twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.phone-number=${TWILIO_PHONE_NUMBER}

notification.max-retries=3




spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.concurrency=3
spring.rabbitmq.listener.simple.max-concurrency=5
spring.rabbitmq.listener.simple.prefetch=1

notification.rabbitmq.exchange=notification.exchange
notification.rabbitmq.queue=notification.queue
notification.rabbitmq.routing-key=notification.routing.key


springdoc.api-docs.path=/openapi.json
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/docs
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.config-url=/openapi.json/swagger-config
springdoc.swagger-ui.url=/openapi.json


