"""add_document_messages_table

Revision ID: 3f29ab9012a6
Revises: b86b7cf3f701
Create Date: 2026-07-19 15:04:48.172223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f29ab9012a6'
down_revision: Union[str, Sequence[str], None] = 'b86b7cf3f701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first
    op.execute("CREATE TYPE conversation_status AS ENUM ('SUGGEREE', 'CONSULTEE', 'EN_CONTACT', 'EN_NEGOCIATION', 'CONCLUE', 'REJETEE')")
    
    op.create_table('document_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('expediteur_id', sa.Integer(), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('type_fichier', sa.String(length=50), nullable=True),
    sa.Column('taille', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['expediteur_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_messages_id'), 'document_messages', ['id'], unique=False)
    # Convert the statut column from VARCHAR to ENUM with explicit casting
    op.execute("ALTER TABLE conversations ALTER COLUMN statut TYPE conversation_status USING statut::conversation_status")
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role_id')
    # Convert back from ENUM to VARCHAR
    op.execute("ALTER TABLE conversations ALTER COLUMN statut TYPE VARCHAR(20) USING statut::text")
    op.drop_index(op.f('ix_document_messages_id'), table_name='document_messages')
    op.drop_table('document_messages')
    op.execute("DROP TYPE conversation_status")
