"""matching integration fields

Revision ID: 833b0df0cc9d
Revises: 0877ecad1719
Create Date: 2026-08-21 17:13:36.859395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '833b0df0cc9d'
down_revision: Union[str, Sequence[str], None] = '0877ecad1719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annonces', sa.Column('quantity_unit', sa.String(length=50), nullable=True))
    op.add_column('annonces', sa.Column('date_disponibilite', sa.Date(), nullable=True))
    op.add_column('annonces', sa.Column('date_limite', sa.Date(), nullable=True))
    op.add_column('companies', sa.Column('reputation_score', sa.Float(), nullable=True))
    op.alter_column('users', 'type_compte',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'type_compte',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('companies', 'reputation_score')
    op.drop_column('annonces', 'date_limite')
    op.drop_column('annonces', 'date_disponibilite')
    op.drop_column('annonces', 'quantity_unit')
    # ### end Alembic commands ###
