"""role user

Revision ID: b86b7cf3f701
Revises: c7e26f0583c4
Create Date: 2026-07-19 00:18:26.811711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86b7cf3f701'
down_revision: Union[str, Sequence[str], None] = 'c7e26f0583c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_logs', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notification_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notification_logs', type_='foreignkey')
    op.drop_column('notification_logs', 'user_id')
    # ### end Alembic commands ###
