"""update relations

Revision ID: c7e26f0583c4
Revises: 567c9c75e372
Create Date: 2026-07-18 20:03:55.543123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e26f0583c4'
down_revision: Union[str, Sequence[str], None] = '567c9c75e372'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_annonces_company_id'), 'annonces', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_annonces_company_id'), table_name='annonces')
    # ### end Alembic commands ###
