"""add stripe columns

Revision ID: c8a6fa85e8d1
Revises: 3f29ab9012a6
Create Date: 2026-07-20 15:00:40.261809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8a6fa85e8d1'
down_revision: Union[str, Sequence[str], None] = '3f29ab9012a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'statut',
               existing_type=postgresql.ENUM('SUGGEREE', 'CONSULTEE', 'EN_CONTACT', 'EN_NEGOCIATION', 'CONCLUE', 'REJETEE', name='conversation_status'),
               nullable=False)
    op.add_column('user_quotas', sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
    op.add_column('user_quotas', sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user_quotas', ['stripe_customer_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_quotas', type_='unique')
    op.drop_column('user_quotas', 'stripe_subscription_id')
    op.drop_column('user_quotas', 'stripe_customer_id')
    op.alter_column('conversations', 'statut',
               existing_type=postgresql.ENUM('SUGGEREE', 'CONSULTEE', 'EN_CONTACT', 'EN_NEGOCIATION', 'CONCLUE', 'REJETEE', name='conversation_status'),
               nullable=True)
    # ### end Alembic commands ###
