"""Initial migration

Revision ID: c249eb0ad662
Revises: 
Create Date: 2026-07-18 14:26:33.016632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c249eb0ad662'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CLIENT', name='role'), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateur_email'), 'utilisateur', ['email'], unique=True)
    op.create_table('entreprise',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('utilisateur_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('EXPORTATEUR', 'IMPORTATEUR', name='typeentreprise'), nullable=False),
    sa.Column('nom_entreprise', sa.String(), nullable=False),
    sa.Column('numero_tva', sa.String(), nullable=True),
    sa.Column('pays', sa.String(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=False),
    sa.Column('statut_validation', sa.Enum('EN_ATTENTE_VALIDATION', 'VALIDE', 'REJETE', 'SUSPENDU', name='statutvalidation'), nullable=True),
    sa.Column('chats_gratuits_restants', sa.Integer(), nullable=True),
    sa.Column('statut_facturation', sa.Enum('GRATUIT', 'LIMITE_ATTEINTE', 'PAIEMENT_USAGE', 'ABONNE', 'ABONNEMENT_EXPIRE', name='statutfacturation'), nullable=True),
    sa.Column('depense_cumulee_usage', sa.Float(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('utilisateur_id')
    )
    op.create_table('annonce',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entreprise_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('OFFRE', 'DEMANDE', name='typeannonce'), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('categorie', sa.String(), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('localisation', sa.String(), nullable=False),
    sa.Column('incoterms', sa.String(), nullable=True),
    sa.Column('delai_livraison', sa.String(), nullable=True),
    sa.Column('documents_urls', sa.String(), nullable=True),
    sa.Column('statut', sa.Enum('ACTIVE', 'SUSPENDUE', 'CLOTUREE', name='statutannonce'), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_maj', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annonce')
    op.drop_table('entreprise')
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.drop_table('utilisateur')
    # ### end Alembic commands ###
