"""Add messaging models

Revision ID: e5c3fb932c0e
Revises: c249eb0ad662
Create Date: 2026-07-31 14:13:06.857482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5c3fb932c0e'
down_revision: Union[str, None] = 'c249eb0ad662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CLIENT', name='role'), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('EXPORTATEUR', 'IMPORTATEUR', name='typecompany'), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('numero_tva', sa.String(), nullable=True),
    sa.Column('pays', sa.String(), nullable=False),
    sa.Column('adresse', sa.String(), nullable=False),
    sa.Column('statut_validation', sa.Enum('EN_ATTENTE_VALIDATION', 'VALIDE', 'REJETE', 'SUSPENDU', name='statutvalidation'), nullable=True),
    sa.Column('chats_gratuits_restants', sa.Integer(), nullable=True),
    sa.Column('statut_facturation', sa.Enum('GRATUIT', 'LIMITE_ATTEINTE', 'PAIEMENT_USAGE', 'ABONNE', 'ABONNEMENT_EXPIRE', name='statutfacturation'), nullable=True),
    sa.Column('depense_cumulee_usage', sa.Float(), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('listings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('OFFRE', 'DEMANDE', name='typelisting'), nullable=False),
    sa.Column('titre', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('categorie', sa.String(), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('quantite', sa.Float(), nullable=False),
    sa.Column('pays', sa.String(), nullable=False),
    sa.Column('incoterms', sa.String(), nullable=True),
    sa.Column('delai_livraison', sa.String(), nullable=True),
    sa.Column('certification', sa.String(), nullable=True),
    sa.Column('documents_urls', sa.String(), nullable=True),
    sa.Column('statut', sa.Enum('ACTIVE', 'SUSPENDUE', 'CLOTUREE', name='statutlisting'), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_maj', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('initiator_company_id', sa.String(), nullable=False),
    sa.Column('statut', sa.Enum('SUGGEREE', 'CONSULTEE', 'EN_CONTACT', 'EN_NEGOCIATION', 'CONCLUE', 'REJETEE', name='statutconversation'), nullable=True),
    sa.Column('date_creation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_maj', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['initiator_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('contenu', sa.String(), nullable=False),
    sa.Column('date_envoi', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_utilisateur_email', table_name='utilisateur')
    op.drop_table('utilisateur')
    op.drop_table('entreprise')
    op.drop_table('annonce')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annonce',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('entreprise_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('OFFRE', 'DEMANDE', name='typeannonce'), autoincrement=False, nullable=False),
    sa.Column('titre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('categorie', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('prix', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('quantite', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('localisation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('incoterms', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('delai_livraison', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('documents_urls', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('statut', postgresql.ENUM('ACTIVE', 'SUSPENDUE', 'CLOTUREE', name='statutannonce'), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('date_maj', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['entreprise_id'], ['entreprise.id'], name='annonce_entreprise_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='annonce_pkey')
    )
    op.create_table('entreprise',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('utilisateur_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('EXPORTATEUR', 'IMPORTATEUR', name='typeentreprise'), autoincrement=False, nullable=False),
    sa.Column('nom_entreprise', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('numero_tva', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pays', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('adresse', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('statut_validation', postgresql.ENUM('EN_ATTENTE_VALIDATION', 'VALIDE', 'REJETE', 'SUSPENDU', name='statutvalidation'), autoincrement=False, nullable=True),
    sa.Column('chats_gratuits_restants', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('statut_facturation', postgresql.ENUM('GRATUIT', 'LIMITE_ATTEINTE', 'PAIEMENT_USAGE', 'ABONNE', 'ABONNEMENT_EXPIRE', name='statutfacturation'), autoincrement=False, nullable=True),
    sa.Column('depense_cumulee_usage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], name='entreprise_utilisateur_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='entreprise_pkey'),
    sa.UniqueConstraint('utilisateur_id', name='entreprise_utilisateur_id_key')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'CLIENT', name='role'), autoincrement=False, nullable=False),
    sa.Column('date_creation', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='utilisateur_pkey')
    )
    op.create_index('ix_utilisateur_email', 'utilisateur', ['email'], unique=True)
    op.drop_table('document_messages')
    op.drop_table('messages')
    op.drop_table('conversations')
    op.drop_table('listings')
    op.drop_table('companies')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
